version: '3.1'

services:
  finance_db:
    image: postgres:11.6
    container_name: finance_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: finance
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data

  finance_api:
    image: node:16
    container_name: finance_api
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    volumes:
      - .:/home/node/app
    ports:
      - "3000:3000"
    command: "yarn dev"